# PR Labeler Configuration for NocoDB Simple Client
# Automatically assigns labels based on file changes

# Size labels based on lines of code changed
size-labels:
  xs: 0-10
  small: 11-50
  medium: 51-200
  large: 201-500
  xl: 501-1000
  xxl: 1001+

# Path-based labeling rules
path-labels:
  # Source code changes
  "src/nocodb_simple_client/":
    - "area: core"
    - "type: enhancement"

  "src/nocodb_simple_client/client.py":
    - "area: client"
    - "component: api"

  "src/nocodb_simple_client/table.py":
    - "area: table"
    - "component: table-operations"

  "src/nocodb_simple_client/exceptions.py":
    - "area: exceptions"
    - "component: error-handling"

  # Test changes
  "tests/":
    - "area: tests"
    - "type: testing"

  "tests/test_client.py":
    - "area: tests"
    - "component: client-tests"

  "tests/test_table.py":
    - "area: tests"
    - "component: table-tests"

  "tests/test_integration.py":
    - "area: tests"
    - "type: integration"
    - "priority: high"

  # Documentation changes
  "README.MD":
    - "area: documentation"
    - "type: documentation"

  "docs/":
    - "area: documentation"
    - "type: documentation"

  "CHANGELOG.MD":
    - "area: documentation"
    - "type: changelog"

  # Examples
  "examples/":
    - "area: examples"
    - "type: documentation"

  # Configuration changes
  "pyproject.toml":
    - "area: build"
    - "type: build"
    - "priority: medium"

  ".github/workflows/":
    - "area: ci/cd"
    - "type: ci"
    - "priority: medium"

  ".github/workflows/ci-cd.yml":
    - "area: ci/cd"
    - "type: ci"
    - "priority: high"

  ".github/workflows/release.yml":
    - "area: ci/cd"
    - "type: release"
    - "priority: high"

  # Security files
  "SECURITY.MD":
    - "area: security"
    - "type: security"
    - "priority: high"

  ".github/workflows/security.yml":
    - "area: security"
    - "type: security"
    - "priority: high"

# Branch-based labeling
branch-labels:
  feature/*:
    - "type: feature"
  fix/*:
    - "type: bugfix"
  hotfix/*:
    - "type: hotfix"
    - "priority: critical"
  chore/*:
    - "type: chore"
  docs/*:
    - "type: documentation"
  test/*:
    - "type: testing"
  ci/*:
    - "type: ci"
  security/*:
    - "type: security"
    - "priority: high"
  refactor/*:
    - "type: refactor"

# Title-based labeling (regex patterns)
title-labels:
  - pattern: "(?i)(breaking|major)"
    labels:
      - "type: breaking-change"
      - "priority: critical"

  - pattern: "(?i)(fix|bug)"
    labels:
      - "type: bugfix"

  - pattern: "(?i)(feat|feature)"
    labels:
      - "type: feature"

  - pattern: "(?i)(doc|documentation)"
    labels:
      - "type: documentation"

  - pattern: "(?i)(test|testing)"
    labels:
      - "type: testing"

  - pattern: "(?i)(security|vulnerability|cve)"
    labels:
      - "type: security"
      - "priority: high"

  - pattern: "(?i)(performance|perf|optimization)"
    labels:
      - "type: performance"

  - pattern: "(?i)(refactor|cleanup)"
    labels:
      - "type: refactor"

  - pattern: "(?i)(ci|workflow|github actions)"
    labels:
      - "type: ci"

# Auto-reviewers based on areas
auto-reviewers:
  "area: core":
    reviewers:
      - "karl.bauer@bauer-group.com"

  "type: security":
    reviewers:
      - "karl.bauer@bauer-group.com"
    review-required: true

  "type: breaking-change":
    reviewers:
      - "karl.bauer@bauer-group.com"
    review-required: true

# Special handling
special-labels:
  draft:
    - "status: draft"

  ready-for-review:
    remove:
      - "status: draft"
    add:
      - "status: ready-for-review"
