name: 🐍 CI/CD Pipeline (Automatic Release)

on:
  # Trigger on push to main branch
  push:
    branches: [main]
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - '*.md'
      - '*.MD'

  # Trigger on pull requests to main
  pull_request:
    branches: [main]
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - '*.md'
      - '*.MD'

  # Manual trigger
  workflow_dispatch:
    inputs:
      skip-pypi:
        description: 'Skip PyPI publishing (GitHub release only)'
        type: boolean
        default: false

jobs:
  python-release:
    name: 🐍 Python Semantic Release Pipeline
    uses: bauer-group/automation-templates/.github/workflows/python-semantic-release.yml@main
    with:
      # Python Configuration
      python-version: '3.12'  # or ['3.10', '3.11', '3.12'] for matrix

      # Testing Configuration
      run-tests: true
      run-security-scan: true

      # Security Configuration
      security-engine: 'both'  # gitleaks, gitguardian, both

      # Build Configuration
      build-local-wheel: true

      # Release Configuration
      skip-pypi: ${{ inputs.skip-pypi || false }}

      # Documentation & Security Updates
      update-documentation: true
      update-security-policy: true

    secrets: inherit
