name: 📢 Teams Notifications

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, closed, reopened]
  release:
    types: [published, prereleased]
  issues:
    types: [opened, closed, reopened]
  workflow_run:
    workflows: ["*"]
    types: [completed]
  workflow_dispatch:
    inputs:
      message:
        description: 'Custom message to send'
        required: true
        type: string
      channel:
        description: 'Teams channel (webhook name)'
        required: false
        type: string
        default: 'general'
  workflow_call:
    inputs:
      custom-message:
        description: 'Custom message to include'
        type: string
        required: false
        default: ''
      webhook-name:
        description: 'Teams webhook secret name'
        type: string
        required: false
        default: 'TEAMS_WEBHOOK_URL'
      include-details:
        description: 'Include detailed information'
        type: boolean
        required: false
        default: true

jobs:
  notify-teams:
    name: Send Teams Notification
    uses: bauer-group/automation-templates/.github/workflows/teams-notifications.yml@main
    with:
      custom-message: ${{ inputs.custom-message || inputs.message }}
      webhook-name: ${{ inputs.webhook-name || 'TEAMS_WEBHOOK_URL' }}
      include-details: ${{ inputs.include-details }}
    secrets: inherit